# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-11 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default='', max_length=5)),
                ('title', models.CharField(default='', max_length=150)),
                ('disclaimer', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GuideItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, upload_to='guide_menu')),
                ('title', models.CharField(default='', max_length=70)),
                ('description', tinymce.models.HTMLField(default='')),
                ('slug', models.CharField(default='', max_length=6)),
                ('remarq', tinymce.models.HTMLField(blank=True, default='')),
                ('content', tinymce.models.HTMLField(blank=True, default='')),
                ('advice', tinymce.models.HTMLField(blank=True, default='')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Guide')),
            ],
        ),
    ]
