# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-02 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20161201_1524'),
        ('coma', '0003_molliepayment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fromWho',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_from', to='members.Member'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_user', to='members.Member'),
        ),
    ]
