# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-02 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coma', '0006_auto_20170201_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'permissions': (('create_purchase', 'Permission to create purchase for anyone.'), ('add_money', 'Permission to add money to account.'))},
        ),
    ]
