# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-11 11:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='Date de début')),
                ('stop', models.DateField(verbose_name='Date de fin')),
                ('slug', models.CharField(max_length=4)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Année académique',
                'ordering': ['-start'],
            },
        ),
        migrations.CreateModel(
            name='ComiteMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ComitePoste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=5)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_bureau', models.BooleanField(default=False)),
                ('is_bapteme', models.BooleanField(default=False)),
                ('weight', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Poste dans le comité',
                'ordering': ['-weight'],
            },
        ),
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Permission',
            },
        ),
        migrations.CreateModel(
            name='CustomPermissionsManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, to='auth.Group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.CustomPermission')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permissions Manager',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images/members', verbose_name='avatar')),
                ('wiki', models.URLField(blank=True, null=True)),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('extra_info', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250)),
                ('is_prefered', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
            ],
        ),
        migrations.AddField(
            model_name='comitemembership',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Member'),
        ),
        migrations.AddField(
            model_name='comitemembership',
            name='poste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.ComitePoste'),
        ),
        migrations.AddField(
            model_name='comitemembership',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.AcademicYear', verbose_name='année'),
        ),
    ]
