# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-11 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comitemembership',
            name='card_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='comitemembership',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comitemembership',
            name='poste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.ComitePoste'),
        ),
        migrations.AlterField(
            model_name='comitemembership',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.AcademicYear', verbose_name='year'),
        ),
    ]
