# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-11 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def combine_memberships_postes(apps, schema_editor):
    Member = apps.get_model('members', 'Member')
    AcademicYear = apps.get_model('members', 'AcademicYear')
    Postes = apps.get_model('members', 'ComiteMembership')
    for year in AcademicYear.objects.all():
        # for each year we will clear the
        for member in Member.objects.all():
            postes = Postes.objects.filter(member=member, year=year)
            if (len(postes)) > 0:
                for poste in postes:
                    poste.postes.add(poste.poste)
                poste.save()


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20160911_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='comitemembership',
            name='postes',
            field=models.ManyToManyField(to='members.ComitePoste'),
        ),
        migrations.AlterField(
            model_name='comitemembership',
            name='poste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_poste', to='members.ComitePoste'),
        ),
        migrations.RunPython(combine_memberships_postes)
    ]
