# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-11 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20160911_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comitemembership',
            name='poste',
        ),
    ]
