# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-11 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_comitemembership_poste'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comitemembership',
            options={'ordering': ['year']},
        ),
        migrations.AlterField(
            model_name='comitemembership',
            name='postes',
            field=models.ManyToManyField(related_name='membership', to='members.ComitePoste'),
        ),
    ]
