# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-24 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20160911_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comitemembership',
            name='card_id',
        ),
    ]
