# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-30 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_member_card_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_bar',
            field=models.BooleanField(default=False),
        ),
    ]
