# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-01 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_member_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
